<?php

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media')->delete();
        
        \DB::table('media')->insert(array (
            0 => 
            array (
                'id' => 17,
                'model_type' => 'App\\Models\\User',
                'model_id' => 7,
                'collection_name' => 'avatar',
                'name' => 'type3 - Copie',
                'file_name' => 'type3---Copie.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 93699,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"f23837ec-ec63-4a35-b9ca-4a2da1a136fa","custom_headers":[],"generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 15,
                'created_at' => '2018-08-06 22:03:06',
                'updated_at' => '2018-08-06 22:03:06',
            ),
            1 => 
            array (
                'id' => 32,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 18,
                'collection_name' => 'avatar',
                'name' => 'user0',
                'file_name' => 'user0.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 27946,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"f090bd7d-1e27-4832-8355-b9dd45c9e9ca","custom_headers":[],"generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 30,
                'created_at' => '2019-08-27 14:58:03',
                'updated_at' => '2019-08-27 14:58:04',
            ),
            2 => 
            array (
                'id' => 34,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 19,
                'collection_name' => 'app_logo',
                'name' => 'ic_launcher',
                'file_name' => 'ic_launcher.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'size' => 18944,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"020a2dd4-4277-425a-b450-426663f52633","custom_headers":[],"generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 32,
                'created_at' => '2019-08-27 14:59:08',
                'updated_at' => '2019-08-27 14:59:09',
            ),
            3 => 
            array (
                'id' => 35,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 20,
                'collection_name' => 'image',
                'name' => 'food3',
                'file_name' => 'food3.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 129114,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"26337c68-3ba4-489d-b417-42f5617fbe10","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 33,
                'created_at' => '2019-08-29 21:54:21',
                'updated_at' => '2019-08-29 21:54:21',
            ),
            4 => 
            array (
                'id' => 37,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 21,
                'collection_name' => 'image',
                'name' => 'food5',
                'file_name' => 'food5.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 95713,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"d6d948be-fb90-43bc-840e-fb0e1af2d253","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 35,
                'created_at' => '2019-08-29 22:32:01',
                'updated_at' => '2019-08-29 22:32:02',
            ),
            5 => 
            array (
                'id' => 39,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 22,
                'collection_name' => 'image',
                'name' => 'food0',
                'file_name' => 'food0.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 102282,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"6131cae4-e0c1-495e-9c09-34ca3ce469f6","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 37,
                'created_at' => '2019-08-29 22:42:48',
                'updated_at' => '2019-08-29 22:42:49',
            ),
            6 => 
            array (
                'id' => 42,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 23,
                'collection_name' => 'image',
                'name' => 'food1',
                'file_name' => 'food1.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 138202,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"f678c87b-5583-4a1c-bdec-4fbde1f3bdca","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 40,
                'created_at' => '2019-08-30 11:07:13',
                'updated_at' => '2019-08-30 11:07:14',
            ),
            7 => 
            array (
                'id' => 44,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 24,
                'collection_name' => 'image',
                'name' => 'food5',
                'file_name' => 'food5.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 95713,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"8e79b31c-1f20-4d30-abee-30627dd707ea","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 42,
                'created_at' => '2019-08-30 11:07:36',
                'updated_at' => '2019-08-30 11:07:36',
            ),
            8 => 
            array (
                'id' => 48,
                'model_type' => 'App\\Models\\Food',
                'model_id' => 1,
                'collection_name' => 'image',
                'name' => 'food1',
                'file_name' => 'food1.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 138202,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"f678c87b-5583-4a1c-bdec-4fbde1f3bdca","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 46,
                'created_at' => '2019-08-30 11:21:43',
                'updated_at' => '2019-08-30 11:21:43',
            ),
            9 => 
            array (
                'id' => 52,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 25,
                'collection_name' => 'image',
                'name' => 'food2',
                'file_name' => 'food2.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 89539,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"02a2bd26-5f72-4089-a87a-2d0c1cad4e35","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 50,
                'created_at' => '2019-08-30 11:41:19',
                'updated_at' => '2019-08-30 11:41:20',
            ),
            10 => 
            array (
                'id' => 54,
                'model_type' => 'App\\Models\\Food',
                'model_id' => 2,
                'collection_name' => 'image',
                'name' => 'food2',
                'file_name' => 'food2.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 89539,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"02a2bd26-5f72-4089-a87a-2d0c1cad4e35","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 52,
                'created_at' => '2019-08-31 12:03:37',
                'updated_at' => '2019-08-31 12:03:37',
            ),
            11 => 
            array (
                'id' => 57,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 26,
                'collection_name' => 'avatar',
                'name' => 'user1',
                'file_name' => 'user1.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 28974,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"c0a791ea-33ed-4002-ac7d-267e08d740da","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 55,
                'created_at' => '2019-09-01 10:47:09',
                'updated_at' => '2019-09-01 10:47:10',
            ),
            12 => 
            array (
                'id' => 59,
                'model_type' => 'App\\Models\\NotificationType',
                'model_id' => 1,
                'collection_name' => 'image',
                'name' => 'food1',
                'file_name' => 'food1.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 138202,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"f678c87b-5583-4a1c-bdec-4fbde1f3bdca","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 57,
                'created_at' => '2019-09-04 13:06:14',
                'updated_at' => '2019-09-04 13:06:14',
            ),
            13 => 
            array (
                'id' => 60,
                'model_type' => 'App\\Models\\NotificationType',
                'model_id' => 2,
                'collection_name' => 'image',
                'name' => 'food0',
                'file_name' => 'food0.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 102282,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"6131cae4-e0c1-495e-9c09-34ca3ce469f6","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 58,
                'created_at' => '2019-09-04 13:06:36',
                'updated_at' => '2019-09-04 13:06:36',
            ),
            14 => 
            array (
                'id' => 61,
                'model_type' => 'App\\Models\\NotificationType',
                'model_id' => 3,
                'collection_name' => 'image',
                'name' => 'food2',
                'file_name' => 'food2.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 89539,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"02a2bd26-5f72-4089-a87a-2d0c1cad4e35","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 59,
                'created_at' => '2019-09-04 13:07:10',
                'updated_at' => '2019-09-04 13:07:10',
            ),
            15 => 
            array (
                'id' => 62,
                'model_type' => 'App\\Models\\User',
                'model_id' => 1,
                'collection_name' => 'avatar',
                'name' => 'user0',
                'file_name' => 'user0.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 27946,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"f090bd7d-1e27-4832-8355-b9dd45c9e9ca","custom_headers":[],"generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 60,
                'created_at' => '2019-09-06 21:38:59',
                'updated_at' => '2019-09-06 21:38:59',
            ),
            16 => 
            array (
                'id' => 65,
                'model_type' => 'App\\Models\\User',
                'model_id' => 19,
                'collection_name' => 'avatar',
                'name' => 'api',
                'file_name' => 'api.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'size' => 796,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"$2y$10$MhJMEFqv6leUxN7oOApXHuUStBVmAbec.it7g1HRt63G7xdNwmmRK","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 63,
                'created_at' => '2019-10-12 21:31:27',
                'updated_at' => '2019-10-12 21:31:28',
            ),
            17 => 
            array (
                'id' => 66,
                'model_type' => 'App\\Models\\User',
                'model_id' => 20,
                'collection_name' => 'avatar',
                'name' => 'api',
                'file_name' => 'api.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'size' => 1208,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"$2y$10$dc7KCWO\\/WQfMEs\\/ulB7ycu\\/rjNGHd2li8rEw5O8bJL1KWAqJE9g0m","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 64,
                'created_at' => '2019-10-15 16:55:40',
                'updated_at' => '2019-10-15 16:55:42',
            ),
            18 => 
            array (
                'id' => 67,
                'model_type' => 'App\\Models\\User',
                'model_id' => 18,
                'collection_name' => 'avatar',
                'name' => 'user1',
                'file_name' => 'user1.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 28974,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"c0a791ea-33ed-4002-ac7d-267e08d740da","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 65,
                'created_at' => '2019-10-16 18:32:09',
                'updated_at' => '2019-10-16 18:32:09',
            ),
            19 => 
            array (
                'id' => 68,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 27,
                'collection_name' => 'image',
                'name' => 'restaurant-3597677_1280',
                'file_name' => 'restaurant-3597677_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 369963,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"76a05190-0d7d-4b24-9100-ff78e0aa04dc","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 66,
                'created_at' => '2019-10-16 18:34:03',
                'updated_at' => '2019-10-16 18:34:04',
            ),
            20 => 
            array (
                'id' => 69,
                'model_type' => 'App\\Models\\Restaurant',
                'model_id' => 2,
                'collection_name' => 'image',
                'name' => 'restaurant-3597677_1280',
                'file_name' => 'restaurant-3597677_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 369963,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"76a05190-0d7d-4b24-9100-ff78e0aa04dc","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 67,
                'created_at' => '2019-10-16 18:34:20',
                'updated_at' => '2019-10-16 18:34:20',
            ),
            21 => 
            array (
                'id' => 70,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 28,
                'collection_name' => 'image',
                'name' => 'restaurant-2649620_1280',
                'file_name' => 'restaurant-2649620_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 441524,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"657d6464-130a-4805-aa97-d1b06f5809f5","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 68,
                'created_at' => '2019-10-16 18:35:31',
                'updated_at' => '2019-10-16 18:35:32',
            ),
            22 => 
            array (
                'id' => 71,
                'model_type' => 'App\\Models\\Restaurant',
                'model_id' => 1,
                'collection_name' => 'image',
                'name' => 'restaurant-2649620_1280',
                'file_name' => 'restaurant-2649620_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 441524,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"657d6464-130a-4805-aa97-d1b06f5809f5","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 69,
                'created_at' => '2019-10-16 18:35:34',
                'updated_at' => '2019-10-16 18:35:34',
            ),
            23 => 
            array (
                'id' => 72,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 29,
                'collection_name' => 'image',
                'name' => 'restaurant-449952_1280',
                'file_name' => 'restaurant-449952_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 289736,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"0a6b49a6-154a-407e-a864-42c22dcf751b","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 70,
                'created_at' => '2019-10-16 18:36:56',
                'updated_at' => '2019-10-16 18:36:57',
            ),
            24 => 
            array (
                'id' => 73,
                'model_type' => 'App\\Models\\Restaurant',
                'model_id' => 3,
                'collection_name' => 'image',
                'name' => 'restaurant-449952_1280',
                'file_name' => 'restaurant-449952_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 289736,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"0a6b49a6-154a-407e-a864-42c22dcf751b","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 71,
                'created_at' => '2019-10-16 18:37:18',
                'updated_at' => '2019-10-16 18:37:18',
            ),
            25 => 
            array (
                'id' => 74,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 30,
                'collection_name' => 'image',
                'name' => 'restaurant-1837150_1920',
                'file_name' => 'restaurant-1837150_1920.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 540709,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"05801bad-536b-47cc-85db-cbd391fd5eab","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 72,
                'created_at' => '2019-10-16 18:37:57',
                'updated_at' => '2019-10-16 18:37:58',
            ),
            26 => 
            array (
                'id' => 75,
                'model_type' => 'App\\Models\\Restaurant',
                'model_id' => 4,
                'collection_name' => 'image',
                'name' => 'restaurant-1837150_1920',
                'file_name' => 'restaurant-1837150_1920.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 540709,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"05801bad-536b-47cc-85db-cbd391fd5eab","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 73,
                'created_at' => '2019-10-16 18:38:18',
                'updated_at' => '2019-10-16 18:38:18',
            ),
            27 => 
            array (
                'id' => 77,
                'model_type' => 'App\\Models\\Gallery',
                'model_id' => 2,
                'collection_name' => 'image',
                'name' => 'restaurant-2649620_1280',
                'file_name' => 'restaurant-2649620_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 441524,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"657d6464-130a-4805-aa97-d1b06f5809f5","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 75,
                'created_at' => '2019-10-16 18:39:07',
                'updated_at' => '2019-10-16 18:39:07',
            ),
            28 => 
            array (
                'id' => 78,
                'model_type' => 'App\\Models\\Gallery',
                'model_id' => 3,
                'collection_name' => 'image',
                'name' => 'restaurant-3597677_1280',
                'file_name' => 'restaurant-3597677_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 369963,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"76a05190-0d7d-4b24-9100-ff78e0aa04dc","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 76,
                'created_at' => '2019-10-16 18:39:42',
                'updated_at' => '2019-10-16 18:39:42',
            ),
            29 => 
            array (
                'id' => 79,
                'model_type' => 'App\\Models\\Gallery',
                'model_id' => 4,
                'collection_name' => 'image',
                'name' => 'restaurant-1837150_1920',
                'file_name' => 'restaurant-1837150_1920.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 540709,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"05801bad-536b-47cc-85db-cbd391fd5eab","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 77,
                'created_at' => '2019-10-16 18:40:20',
                'updated_at' => '2019-10-16 18:40:20',
            ),
            30 => 
            array (
                'id' => 80,
                'model_type' => 'App\\Models\\Gallery',
                'model_id' => 5,
                'collection_name' => 'image',
                'name' => 'restaurant-2649620_1280',
                'file_name' => 'restaurant-2649620_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 441524,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"657d6464-130a-4805-aa97-d1b06f5809f5","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 78,
                'created_at' => '2019-10-16 18:40:38',
                'updated_at' => '2019-10-16 18:40:38',
            ),
            31 => 
            array (
                'id' => 81,
                'model_type' => 'App\\Models\\Gallery',
                'model_id' => 6,
                'collection_name' => 'image',
                'name' => 'restaurant-3597677_1280',
                'file_name' => 'restaurant-3597677_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 369963,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"76a05190-0d7d-4b24-9100-ff78e0aa04dc","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 79,
                'created_at' => '2019-10-16 18:40:56',
                'updated_at' => '2019-10-16 18:40:56',
            ),
            32 => 
            array (
                'id' => 82,
                'model_type' => 'App\\Models\\Gallery',
                'model_id' => 7,
                'collection_name' => 'image',
                'name' => 'restaurant-1837150_1920',
                'file_name' => 'restaurant-1837150_1920.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 540709,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"05801bad-536b-47cc-85db-cbd391fd5eab","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 80,
                'created_at' => '2019-10-16 18:41:41',
                'updated_at' => '2019-10-16 18:41:41',
            ),
            33 => 
            array (
                'id' => 83,
                'model_type' => 'App\\Models\\Gallery',
                'model_id' => 8,
                'collection_name' => 'image',
                'name' => 'restaurant-449952_1280',
                'file_name' => 'restaurant-449952_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 289736,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"0a6b49a6-154a-407e-a864-42c22dcf751b","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 81,
                'created_at' => '2019-10-16 18:41:56',
                'updated_at' => '2019-10-16 18:41:56',
            ),
            34 => 
            array (
                'id' => 84,
                'model_type' => 'App\\Models\\Gallery',
                'model_id' => 9,
                'collection_name' => 'image',
                'name' => 'restaurant-3597677_1280',
                'file_name' => 'restaurant-3597677_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 369963,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"76a05190-0d7d-4b24-9100-ff78e0aa04dc","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 82,
                'created_at' => '2019-10-16 18:42:12',
                'updated_at' => '2019-10-16 18:42:12',
            ),
            35 => 
            array (
                'id' => 85,
                'model_type' => 'App\\Models\\Gallery',
                'model_id' => 10,
                'collection_name' => 'image',
                'name' => 'restaurant-3597677_1280',
                'file_name' => 'restaurant-3597677_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 369963,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"76a05190-0d7d-4b24-9100-ff78e0aa04dc","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 83,
                'created_at' => '2019-10-16 18:42:24',
                'updated_at' => '2019-10-16 18:42:24',
            ),
            36 => 
            array (
                'id' => 86,
                'model_type' => 'App\\Models\\Gallery',
                'model_id' => 11,
                'collection_name' => 'image',
                'name' => 'restaurant-449952_1280',
                'file_name' => 'restaurant-449952_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 289736,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"0a6b49a6-154a-407e-a864-42c22dcf751b","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 84,
                'created_at' => '2019-10-16 18:42:38',
                'updated_at' => '2019-10-16 18:42:38',
            ),
            37 => 
            array (
                'id' => 87,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 31,
                'collection_name' => 'image',
                'name' => 'extra1',
                'file_name' => 'extra1.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 7578,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"2dedc2c0-a47b-4bc6-a9dd-c36f41d8949b","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 85,
                'created_at' => '2019-10-16 18:49:08',
                'updated_at' => '2019-10-16 18:49:08',
            ),
            38 => 
            array (
                'id' => 88,
                'model_type' => 'App\\Models\\Extra',
                'model_id' => 2,
                'collection_name' => 'image',
                'name' => 'extra1',
                'file_name' => 'extra1.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 7578,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"2dedc2c0-a47b-4bc6-a9dd-c36f41d8949b","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 86,
                'created_at' => '2019-10-16 18:49:15',
                'updated_at' => '2019-10-16 18:49:15',
            ),
            39 => 
            array (
                'id' => 89,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 32,
                'collection_name' => 'image',
                'name' => 'extra3',
                'file_name' => 'extra3.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 19323,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"09f3a00a-d451-46d0-b200-f33fb09fcdf5","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 87,
                'created_at' => '2019-10-16 18:49:39',
                'updated_at' => '2019-10-16 18:49:40',
            ),
            40 => 
            array (
                'id' => 90,
                'model_type' => 'App\\Models\\Extra',
                'model_id' => 1,
                'collection_name' => 'image',
                'name' => 'extra3',
                'file_name' => 'extra3.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 19323,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"09f3a00a-d451-46d0-b200-f33fb09fcdf5","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 88,
                'created_at' => '2019-10-16 18:49:46',
                'updated_at' => '2019-10-16 18:49:46',
            ),
            41 => 
            array (
                'id' => 91,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 33,
                'collection_name' => 'image',
                'name' => 'extra5',
                'file_name' => 'extra5.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 17578,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"de3dbcd2-cbef-44ce-a63d-acdeba07f8db","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 89,
                'created_at' => '2019-10-16 18:50:11',
                'updated_at' => '2019-10-16 18:50:13',
            ),
            42 => 
            array (
                'id' => 92,
                'model_type' => 'App\\Models\\Extra',
                'model_id' => 3,
                'collection_name' => 'image',
                'name' => 'extra5',
                'file_name' => 'extra5.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 17578,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"de3dbcd2-cbef-44ce-a63d-acdeba07f8db","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 90,
                'created_at' => '2019-10-16 18:50:16',
                'updated_at' => '2019-10-16 18:50:16',
            ),
            43 => 
            array (
                'id' => 93,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 34,
                'collection_name' => 'image',
                'name' => 'extra4',
                'file_name' => 'extra4.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 11839,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"06a22ca5-b0d0-4037-84b8-de56544b5603","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 91,
                'created_at' => '2019-10-16 18:50:34',
                'updated_at' => '2019-10-16 18:50:34',
            ),
            44 => 
            array (
                'id' => 94,
                'model_type' => 'App\\Models\\Extra',
                'model_id' => 4,
                'collection_name' => 'image',
                'name' => 'extra4',
                'file_name' => 'extra4.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 11839,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"06a22ca5-b0d0-4037-84b8-de56544b5603","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 92,
                'created_at' => '2019-10-16 18:50:53',
                'updated_at' => '2019-10-16 18:50:53',
            ),
            45 => 
            array (
                'id' => 95,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 35,
                'collection_name' => 'image',
                'name' => 'margherita-pizza-993274_1280',
                'file_name' => 'margherita-pizza-993274_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 237678,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"793eed7b-c814-441c-9bed-05f325a3c40f","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 93,
                'created_at' => '2019-10-17 22:04:25',
                'updated_at' => '2019-10-17 22:04:27',
            ),
            46 => 
            array (
                'id' => 96,
                'model_type' => 'App\\Models\\Food',
                'model_id' => 3,
                'collection_name' => 'image',
                'name' => 'margherita-pizza-993274_1280',
                'file_name' => 'margherita-pizza-993274_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 237678,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"793eed7b-c814-441c-9bed-05f325a3c40f","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 94,
                'created_at' => '2019-10-17 22:06:52',
                'updated_at' => '2019-10-17 22:06:52',
            ),
            47 => 
            array (
                'id' => 97,
                'model_type' => 'App\\Models\\Extra',
                'model_id' => 5,
                'collection_name' => 'image',
                'name' => 'extra4',
                'file_name' => 'extra4.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 11839,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"06a22ca5-b0d0-4037-84b8-de56544b5603","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 95,
                'created_at' => '2019-10-17 22:10:01',
                'updated_at' => '2019-10-17 22:10:01',
            ),
            48 => 
            array (
                'id' => 98,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 36,
                'collection_name' => 'image',
                'name' => 'pizza-2000615_1280',
                'file_name' => 'pizza-2000615_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 335428,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"a261347a-3dfa-4d4d-86e9-85bd442a2b50","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 96,
                'created_at' => '2019-10-18 09:09:45',
                'updated_at' => '2019-10-18 09:09:47',
            ),
            49 => 
            array (
                'id' => 99,
                'model_type' => 'App\\Models\\Food',
                'model_id' => 4,
                'collection_name' => 'image',
                'name' => 'pizza-2000615_1280',
                'file_name' => 'pizza-2000615_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 335428,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"a261347a-3dfa-4d4d-86e9-85bd442a2b50","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 97,
                'created_at' => '2019-10-18 09:09:53',
                'updated_at' => '2019-10-18 09:09:53',
            ),
            50 => 
            array (
                'id' => 100,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 37,
                'collection_name' => 'image',
                'name' => 'pizza-2802332_1280',
                'file_name' => 'pizza-2802332_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 450717,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"fe38c3e7-6d6f-4b53-94aa-b1ebe5970854","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 98,
                'created_at' => '2019-10-18 09:14:17',
                'updated_at' => '2019-10-18 09:14:18',
            ),
            51 => 
            array (
                'id' => 101,
                'model_type' => 'App\\Models\\Food',
                'model_id' => 5,
                'collection_name' => 'image',
                'name' => 'pizza-2802332_1280',
                'file_name' => 'pizza-2802332_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 450717,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"fe38c3e7-6d6f-4b53-94aa-b1ebe5970854","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 99,
                'created_at' => '2019-10-18 09:15:19',
                'updated_at' => '2019-10-18 09:15:19',
            ),
            52 => 
            array (
                'id' => 102,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 38,
                'collection_name' => 'image',
                'name' => 'pizza-1081543_1280',
                'file_name' => 'pizza-1081543_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 175543,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"6b658af2-efff-40d0-ba94-58a545fcade7","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 100,
                'created_at' => '2019-10-18 09:15:35',
                'updated_at' => '2019-10-18 09:15:35',
            ),
            53 => 
            array (
                'id' => 103,
                'model_type' => 'App\\Models\\Food',
                'model_id' => 6,
                'collection_name' => 'image',
                'name' => 'pizza-1081543_1280',
                'file_name' => 'pizza-1081543_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 175543,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"6b658af2-efff-40d0-ba94-58a545fcade7","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 101,
                'created_at' => '2019-10-18 09:16:17',
                'updated_at' => '2019-10-18 09:16:17',
            ),
            54 => 
            array (
                'id' => 104,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 39,
                'collection_name' => 'image',
                'name' => 'pasta-712664_1280',
                'file_name' => 'pasta-712664_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 261150,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"9120de78-3d31-4934-9bdc-5199baee264d","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 102,
                'created_at' => '2019-10-18 09:19:19',
                'updated_at' => '2019-10-18 09:19:20',
            ),
            55 => 
            array (
                'id' => 105,
                'model_type' => 'App\\Models\\Food',
                'model_id' => 7,
                'collection_name' => 'image',
                'name' => 'pasta-712664_1280',
                'file_name' => 'pasta-712664_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 261150,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"9120de78-3d31-4934-9bdc-5199baee264d","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 103,
                'created_at' => '2019-10-18 09:19:33',
                'updated_at' => '2019-10-18 09:19:33',
            ),
            56 => 
            array (
                'id' => 106,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 40,
                'collection_name' => 'image',
                'name' => 'spaghetti-709337_1280',
                'file_name' => 'spaghetti-709337_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 220613,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"86e07703-c20b-4986-a401-c03f82203264","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 104,
                'created_at' => '2019-10-18 09:35:16',
                'updated_at' => '2019-10-18 09:35:17',
            ),
            57 => 
            array (
                'id' => 107,
                'model_type' => 'App\\Models\\Food',
                'model_id' => 8,
                'collection_name' => 'image',
                'name' => 'spaghetti-709337_1280',
                'file_name' => 'spaghetti-709337_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 220613,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"86e07703-c20b-4986-a401-c03f82203264","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 105,
                'created_at' => '2019-10-18 09:36:17',
                'updated_at' => '2019-10-18 09:36:17',
            ),
            58 => 
            array (
                'id' => 108,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 41,
                'collection_name' => 'image',
                'name' => 'spaghetti-3547078_1280',
                'file_name' => 'spaghetti-3547078_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 226745,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"c4483eb7-f84b-4791-925c-e257bbb8cf18","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 106,
                'created_at' => '2019-10-18 09:46:58',
                'updated_at' => '2019-10-18 09:46:58',
            ),
            59 => 
            array (
                'id' => 109,
                'model_type' => 'App\\Models\\Food',
                'model_id' => 9,
                'collection_name' => 'image',
                'name' => 'spaghetti-3547078_1280',
                'file_name' => 'spaghetti-3547078_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 226745,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"c4483eb7-f84b-4791-925c-e257bbb8cf18","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 107,
                'created_at' => '2019-10-18 09:47:46',
                'updated_at' => '2019-10-18 09:47:46',
            ),
            60 => 
            array (
                'id' => 110,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 42,
                'collection_name' => 'image',
                'name' => 'pasta-329521_1280',
                'file_name' => 'pasta-329521_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 195843,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"cd5f8506-d4b6-4dd8-908e-2e1a9f5e5ef9","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 108,
                'created_at' => '2019-10-18 09:48:30',
                'updated_at' => '2019-10-18 09:48:31',
            ),
            61 => 
            array (
                'id' => 111,
                'model_type' => 'App\\Models\\Food',
                'model_id' => 10,
                'collection_name' => 'image',
                'name' => 'pasta-329521_1280',
                'file_name' => 'pasta-329521_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 195843,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"cd5f8506-d4b6-4dd8-908e-2e1a9f5e5ef9","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 109,
                'created_at' => '2019-10-18 09:49:08',
                'updated_at' => '2019-10-18 09:49:08',
            ),
            62 => 
            array (
                'id' => 112,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 43,
                'collection_name' => 'image',
                'name' => 'soup-4115245_1280',
                'file_name' => 'soup-4115245_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 222194,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"6d450cd5-b522-4b0a-8925-966afc4a6872","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 110,
                'created_at' => '2019-10-18 09:51:04',
                'updated_at' => '2019-10-18 09:51:04',
            ),
            63 => 
            array (
                'id' => 113,
                'model_type' => 'App\\Models\\Food',
                'model_id' => 11,
                'collection_name' => 'image',
                'name' => 'soup-4115245_1280',
                'file_name' => 'soup-4115245_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 222194,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"6d450cd5-b522-4b0a-8925-966afc4a6872","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 111,
                'created_at' => '2019-10-18 09:52:28',
                'updated_at' => '2019-10-18 09:52:28',
            ),
            64 => 
            array (
                'id' => 114,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 44,
                'collection_name' => 'image',
                'name' => 'soup-918422_1280',
                'file_name' => 'soup-918422_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 157729,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"b7163204-acbc-41a5-adfd-df6e8c0a8f59","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 112,
                'created_at' => '2019-10-18 09:53:46',
                'updated_at' => '2019-10-18 09:53:46',
            ),
            65 => 
            array (
                'id' => 115,
                'model_type' => 'App\\Models\\Food',
                'model_id' => 12,
                'collection_name' => 'image',
                'name' => 'soup-918422_1280',
                'file_name' => 'soup-918422_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 157729,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"b7163204-acbc-41a5-adfd-df6e8c0a8f59","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 113,
                'created_at' => '2019-10-18 09:54:32',
                'updated_at' => '2019-10-18 09:54:32',
            ),
            66 => 
            array (
                'id' => 116,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 45,
                'collection_name' => 'image',
                'name' => 'soup-1503117_1280',
                'file_name' => 'soup-1503117_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 240711,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"91232db0-e160-419c-aa6b-c7705a6283d5","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 114,
                'created_at' => '2019-10-18 09:56:51',
                'updated_at' => '2019-10-18 09:56:51',
            ),
            67 => 
            array (
                'id' => 117,
                'model_type' => 'App\\Models\\Food',
                'model_id' => 13,
                'collection_name' => 'image',
                'name' => 'soup-1503117_1280',
                'file_name' => 'soup-1503117_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 240711,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"91232db0-e160-419c-aa6b-c7705a6283d5","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 115,
                'created_at' => '2019-10-18 09:57:54',
                'updated_at' => '2019-10-18 09:57:54',
            ),
            68 => 
            array (
                'id' => 118,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 46,
                'collection_name' => 'image',
                'name' => 'hamburger-993526_1280',
                'file_name' => 'hamburger-993526_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 234359,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"76184023-5516-4847-81e7-28e0e2b5e590","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 116,
                'created_at' => '2019-10-18 09:59:07',
                'updated_at' => '2019-10-18 09:59:08',
            ),
            69 => 
            array (
                'id' => 119,
                'model_type' => 'App\\Models\\Food',
                'model_id' => 14,
                'collection_name' => 'image',
                'name' => 'hamburger-993526_1280',
                'file_name' => 'hamburger-993526_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 234359,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"76184023-5516-4847-81e7-28e0e2b5e590","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 117,
                'created_at' => '2019-10-18 10:01:09',
                'updated_at' => '2019-10-18 10:01:09',
            ),
            70 => 
            array (
                'id' => 120,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 47,
                'collection_name' => 'image',
                'name' => 'hamburger-1414423_1280',
                'file_name' => 'hamburger-1414423_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 295610,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"f1fb4002-bca7-488e-b3a4-7c67e635ef21","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 118,
                'created_at' => '2019-10-18 10:48:10',
                'updated_at' => '2019-10-18 10:48:10',
            ),
            71 => 
            array (
                'id' => 121,
                'model_type' => 'App\\Models\\Food',
                'model_id' => 15,
                'collection_name' => 'image',
                'name' => 'hamburger-1414423_1280',
                'file_name' => 'hamburger-1414423_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 295610,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"f1fb4002-bca7-488e-b3a4-7c67e635ef21","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 119,
                'created_at' => '2019-10-18 10:49:36',
                'updated_at' => '2019-10-18 10:49:36',
            ),
            72 => 
            array (
                'id' => 122,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 48,
                'collection_name' => 'image',
                'name' => 'salmon-518032_1280',
                'file_name' => 'salmon-518032_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 227975,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"8e032da7-a5b7-4f6c-a02a-9a0902f81224","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 120,
                'created_at' => '2019-10-18 10:50:15',
                'updated_at' => '2019-10-18 10:50:15',
            ),
            73 => 
            array (
                'id' => 123,
                'model_type' => 'App\\Models\\Food',
                'model_id' => 16,
                'collection_name' => 'image',
                'name' => 'salmon-518032_1280',
                'file_name' => 'salmon-518032_1280.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 227975,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"8e032da7-a5b7-4f6c-a02a-9a0902f81224","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 121,
                'created_at' => '2019-10-18 10:51:51',
                'updated_at' => '2019-10-18 10:51:51',
            ),
            74 => 
            array (
                'id' => 124,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 49,
                'collection_name' => 'image',
                'name' => 'extra7',
                'file_name' => 'extra7.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 10574,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"be0393c4-d89d-4742-9d7c-a175b838c624","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 122,
                'created_at' => '2019-10-18 10:53:09',
                'updated_at' => '2019-10-18 10:53:09',
            ),
            75 => 
            array (
                'id' => 125,
                'model_type' => 'App\\Models\\Extra',
                'model_id' => 6,
                'collection_name' => 'image',
                'name' => 'extra7',
                'file_name' => 'extra7.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 10574,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"be0393c4-d89d-4742-9d7c-a175b838c624","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 123,
                'created_at' => '2019-10-18 10:53:34',
                'updated_at' => '2019-10-18 10:53:34',
            ),
            76 => 
            array (
                'id' => 126,
                'model_type' => 'App\\Models\\Extra',
                'model_id' => 7,
                'collection_name' => 'image',
                'name' => 'extra7',
                'file_name' => 'extra7.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 10574,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"be0393c4-d89d-4742-9d7c-a175b838c624","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 124,
                'created_at' => '2019-10-18 10:54:11',
                'updated_at' => '2019-10-18 10:54:11',
            ),
            77 => 
            array (
                'id' => 127,
                'model_type' => 'App\\Models\\Extra',
                'model_id' => 8,
                'collection_name' => 'image',
                'name' => 'extra7',
                'file_name' => 'extra7.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 10574,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"be0393c4-d89d-4742-9d7c-a175b838c624","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 125,
                'created_at' => '2019-10-18 10:54:37',
                'updated_at' => '2019-10-18 10:54:37',
            ),
            78 => 
            array (
                'id' => 128,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 50,
                'collection_name' => 'image',
                'name' => 'apple',
                'file_name' => 'apple.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'public',
                'size' => 2206,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"d3ee0634-cb13-4184-8fd6-c9ee2d943f3b","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 126,
                'created_at' => '2019-10-18 11:01:29',
                'updated_at' => '2019-10-18 11:01:29',
            ),
            79 => 
            array (
                'id' => 130,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 51,
                'collection_name' => 'image',
                'name' => 'hamburguer-1',
                'file_name' => 'hamburguer-1.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'public',
                'size' => 4161,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"9f3a2ba1-50be-44f5-b01f-d0f50bc39b43","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 128,
                'created_at' => '2019-10-18 11:25:51',
                'updated_at' => '2019-10-18 11:25:52',
            ),
            80 => 
            array (
                'id' => 131,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 2,
                'collection_name' => 'image',
                'name' => 'hamburguer-1',
                'file_name' => 'hamburguer-1.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'public',
                'size' => 4161,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"9f3a2ba1-50be-44f5-b01f-d0f50bc39b43","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 129,
                'created_at' => '2019-10-18 11:25:54',
                'updated_at' => '2019-10-18 11:25:54',
            ),
            81 => 
            array (
                'id' => 132,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 52,
                'collection_name' => 'image',
                'name' => 'milk',
                'file_name' => 'milk.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'public',
                'size' => 3190,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"99ee10c4-81a5-479e-95b1-23e7c35c9b95","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 130,
                'created_at' => '2019-10-18 11:26:48',
                'updated_at' => '2019-10-18 11:26:48',
            ),
            82 => 
            array (
                'id' => 133,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 1,
                'collection_name' => 'image',
                'name' => 'milk',
                'file_name' => 'milk.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'public',
                'size' => 3190,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"99ee10c4-81a5-479e-95b1-23e7c35c9b95","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 131,
                'created_at' => '2019-10-18 11:26:50',
                'updated_at' => '2019-10-18 11:26:50',
            ),
            83 => 
            array (
                'id' => 134,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 53,
                'collection_name' => 'image',
                'name' => 'raspberry',
                'file_name' => 'raspberry.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'public',
                'size' => 4987,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"a54b4a31-ebfb-4a90-a57a-0e74d5c5b25f","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 132,
                'created_at' => '2019-10-18 11:27:16',
                'updated_at' => '2019-10-18 11:27:16',
            ),
            84 => 
            array (
                'id' => 135,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 4,
                'collection_name' => 'image',
                'name' => 'raspberry',
                'file_name' => 'raspberry.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'public',
                'size' => 4987,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"a54b4a31-ebfb-4a90-a57a-0e74d5c5b25f","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 133,
                'created_at' => '2019-10-18 11:27:17',
                'updated_at' => '2019-10-18 11:27:17',
            ),
            85 => 
            array (
                'id' => 136,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 54,
                'collection_name' => 'image',
                'name' => 'cupcake-1',
                'file_name' => 'cupcake-1.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'public',
                'size' => 4170,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"321342a0-5c0a-4960-a082-52d92185dc01","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 134,
                'created_at' => '2019-10-18 11:28:06',
                'updated_at' => '2019-10-18 11:28:06',
            ),
            86 => 
            array (
                'id' => 137,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 5,
                'collection_name' => 'image',
                'name' => 'cupcake-1',
                'file_name' => 'cupcake-1.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'public',
                'size' => 4170,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"321342a0-5c0a-4960-a082-52d92185dc01","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 135,
                'created_at' => '2019-10-18 11:28:08',
                'updated_at' => '2019-10-18 11:28:08',
            ),
            87 => 
            array (
                'id' => 138,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 55,
                'collection_name' => 'image',
                'name' => 'food',
                'file_name' => 'food.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'public',
                'size' => 3483,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"b5a61bc0-5b19-4236-8be5-39320cb41f37","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 136,
                'created_at' => '2019-10-18 11:29:57',
                'updated_at' => '2019-10-18 11:29:58',
            ),
            88 => 
            array (
                'id' => 139,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 3,
                'collection_name' => 'image',
                'name' => 'food',
                'file_name' => 'food.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'public',
                'size' => 3483,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"b5a61bc0-5b19-4236-8be5-39320cb41f37","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 137,
                'created_at' => '2019-10-18 11:29:59',
                'updated_at' => '2019-10-18 11:29:59',
            ),
            89 => 
            array (
                'id' => 140,
                'model_type' => 'App\\Models\\Extra',
                'model_id' => 9,
                'collection_name' => 'image',
                'name' => 'extra3',
                'file_name' => 'extra3.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 19323,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"09f3a00a-d451-46d0-b200-f33fb09fcdf5","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 138,
                'created_at' => '2019-10-18 11:38:44',
                'updated_at' => '2019-10-18 11:38:44',
            ),
            90 => 
            array (
                'id' => 141,
                'model_type' => 'App\\Models\\Extra',
                'model_id' => 10,
                'collection_name' => 'image',
                'name' => 'extra3',
                'file_name' => 'extra3.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 19323,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"09f3a00a-d451-46d0-b200-f33fb09fcdf5","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 139,
                'created_at' => '2019-10-18 11:39:15',
                'updated_at' => '2019-10-18 11:39:15',
            ),
            91 => 
            array (
                'id' => 142,
                'model_type' => 'App\\Models\\Extra',
                'model_id' => 11,
                'collection_name' => 'image',
                'name' => 'extra4',
                'file_name' => 'extra4.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 11839,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"06a22ca5-b0d0-4037-84b8-de56544b5603","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 140,
                'created_at' => '2019-10-18 11:39:46',
                'updated_at' => '2019-10-18 11:39:46',
            ),
            92 => 
            array (
                'id' => 143,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 56,
                'collection_name' => 'avatar',
                'name' => 'picture',
                'file_name' => 'picture.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 24757,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"EAAHXfy36ys8BAM3PAOFmRZAxwqQoXLCnZBQ9SSFi29PKs7t1MmZCWaZBOfDTJb8hM1rACizSwwgCXmI8R7wyDtRYVIejfkxjAEoxYcJj5gcP3rztQlh5fyybYlbZCd8cT6BfqPWBV7D8memSAhAGbGqAatG6AhuQMRdXVa0ce8AZDZD","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 141,
                'created_at' => '2019-10-22 17:05:38',
                'updated_at' => '2019-10-22 17:05:39',
            ),
            93 => 
            array (
                'id' => 145,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 57,
                'collection_name' => 'image',
                'name' => '15717615733623368546809485806768',
                'file_name' => '15717615733623368546809485806768.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 5054079,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"612f979d-ad43-4409-ab6c-c0e1f177bc13"}',
                'responsive_images' => '[]',
                'order_column' => 143,
                'created_at' => '2019-10-22 17:26:36',
                'updated_at' => '2019-10-22 17:26:36',
            ),
            94 => 
            array (
                'id' => 146,
                'model_type' => 'App\\Models\\Gallery',
                'model_id' => 12,
                'collection_name' => 'image',
                'name' => '15717615733623368546809485806768',
                'file_name' => '15717615733623368546809485806768.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 5054079,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"612f979d-ad43-4409-ab6c-c0e1f177bc13"}',
                'responsive_images' => '[]',
                'order_column' => 144,
                'created_at' => '2019-10-22 17:27:00',
                'updated_at' => '2019-10-22 17:27:00',
            ),
            95 => 
            array (
                'id' => 147,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 58,
                'collection_name' => 'default',
                'name' => 'Picture1',
                'file_name' => 'Picture1.png',
                'mime_type' => 'image/png',
                'disk' => 'public',
                'size' => 100206,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"7b475ea8-536e-4919-bba2-9796ffef4f21","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 145,
                'created_at' => '2019-10-22 17:55:29',
                'updated_at' => '2019-10-22 17:55:29',
            ),
            96 => 
            array (
                'id' => 148,
                'model_type' => 'App\\Models\\Upload',
                'model_id' => 59,
                'collection_name' => 'default',
                'name' => '_DSC7564',
                'file_name' => '_DSC7564.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'size' => 2049573,
                'manipulations' => '[]',
                'custom_properties' => '{"uuid":"a396e9f2-4b5c-4fe0-ba7c-d99947b7047e","generated_conversions":{"thumb":true,"icon":true}}',
                'responsive_images' => '[]',
                'order_column' => 146,
                'created_at' => '2019-10-22 18:54:14',
                'updated_at' => '2019-10-22 18:54:31',
            ),
        ));
        
        
    }
}